import { vi } from "vitest";

const {
  mockedFindLearnerProfileById,
  mockedFindLearnerProfileByIdentity,
  mockedListLearnerProfilesForRecordLookup,
  mockedFindTenantAuthPolicy,
  mockedGetTenantReportingComparisons,
  mockedGetTenantReportingEngagementCounts,
  mockedListTenantAuthProviders,
  mockedListTenantBreakGlassAccounts,
  mockedFindTenantLmsConnectionById,
  mockedListTenantLmsConnections,
  mockedListTenantMembers,
  mockedListImportLearnerRecordBatchQueueMessages,
  mockedCreateLearnerRecordImportPreview,
  mockedEnqueueJobQueueMessageOnce,
  mockedFindActiveLearnerRecordImportPreview,
  mockedMarkLearnerRecordImportPreviewQueued,
  mockedListAccessibleTenantContextsForUser,
  mockedListLearnerRecordAssertionExports,
  mockedListLearnerRecordEntries,
  mockedGetTenantReportingOverview,
  mockedGetTenantReportingTrends,
  mockedResolveBetterAuthPrincipal,
  mockedResolveBetterAuthRequestedTenant,
  mockedDeleteDraftBadgeIssuanceRule,
  mockedDecideBadgeIssuanceRuleVersion,
  mockedReopenApprovedBadgeIssuanceRuleVersion,
  mockedWithdrawBadgeIssuanceRuleVersionSubmission,
  mockedRecertifyBadgeIssuanceRuleVersion,
  mockedFindBadgeIssuanceRuleBuilderDraft,
  mockedListBadgeIssuanceRuleBuilderDraftsForUser,
  mockedDeleteBadgeIssuanceRuleBuilderDraftById,
  mockedFindBadgeIssuanceRuleVersionById,
  mockedFindLtiResourceLinkPlacementForRule,
  mockedListBadgeIssuanceRuleVersionApprovalSteps,
  mockedListBadgeIssuanceRuleVersionApprovalEvents,
  mockedListActiveLtiLaunchSessionsForPlatform,
  mockedListPendingBadgeIssuanceRuleApprovalsForActor,
  mockedSubmitBadgeIssuanceRuleVersionForApproval,
  mockedResolveBadgeRuleApprovalPolicy,
  mockedResolveTenantDefaultBadgeRuleApprovalPolicy,
  mockedUpsertBadgeRuleApprovalPolicy,
  mockedCreateBadgeRuleApproverGroup,
  mockedAddBadgeRuleApproverGroupMember,
  mockedListBadgeRuleApproverGroupsWithMembers,
  mockedRemoveBadgeRuleApproverGroupMember,
  mockedRemoveBadgeRuleApproverGroup,
} = vi.hoisted(() => {
  return {
    mockedFindLearnerProfileById: vi.fn(),
    mockedFindLearnerProfileByIdentity: vi.fn(),
    mockedListLearnerProfilesForRecordLookup: vi.fn(),
    mockedFindTenantAuthPolicy: vi.fn(),
    mockedGetTenantReportingComparisons: vi.fn(),
    mockedGetTenantReportingEngagementCounts: vi.fn(),
    mockedListTenantAuthProviders: vi.fn(),
    mockedListTenantBreakGlassAccounts: vi.fn(),
    mockedFindTenantLmsConnectionById: vi.fn(),
    mockedListTenantLmsConnections: vi.fn(),
    mockedListTenantMembers: vi.fn(),
    mockedListImportLearnerRecordBatchQueueMessages: vi.fn(),
    mockedCreateLearnerRecordImportPreview: vi.fn(),
    mockedEnqueueJobQueueMessageOnce: vi.fn(),
    mockedFindActiveLearnerRecordImportPreview: vi.fn(),
    mockedMarkLearnerRecordImportPreviewQueued: vi.fn(),
    mockedListAccessibleTenantContextsForUser: vi.fn(),
    mockedListLearnerRecordAssertionExports: vi.fn(),
    mockedListLearnerRecordEntries: vi.fn(),
    mockedGetTenantReportingOverview: vi.fn(),
    mockedGetTenantReportingTrends: vi.fn(),
    mockedResolveBetterAuthPrincipal: vi.fn(),
    mockedResolveBetterAuthRequestedTenant: vi.fn(),
    mockedDeleteDraftBadgeIssuanceRule: vi.fn(),
    mockedDecideBadgeIssuanceRuleVersion: vi.fn(),
    mockedReopenApprovedBadgeIssuanceRuleVersion: vi.fn(),
    mockedWithdrawBadgeIssuanceRuleVersionSubmission: vi.fn(),
    mockedRecertifyBadgeIssuanceRuleVersion: vi.fn(),
    mockedFindBadgeIssuanceRuleBuilderDraft: vi.fn(),
    mockedListBadgeIssuanceRuleBuilderDraftsForUser: vi.fn(),
    mockedDeleteBadgeIssuanceRuleBuilderDraftById: vi.fn(),
    mockedFindBadgeIssuanceRuleVersionById: vi.fn(),
    mockedFindLtiResourceLinkPlacementForRule: vi.fn(),
    mockedListBadgeIssuanceRuleVersionApprovalSteps: vi.fn(),
    mockedListBadgeIssuanceRuleVersionApprovalEvents: vi.fn(),
    mockedListActiveLtiLaunchSessionsForPlatform: vi.fn(),
    mockedListPendingBadgeIssuanceRuleApprovalsForActor: vi.fn(),
    mockedSubmitBadgeIssuanceRuleVersionForApproval: vi.fn(),
    mockedResolveBadgeRuleApprovalPolicy: vi.fn(),
    mockedResolveTenantDefaultBadgeRuleApprovalPolicy: vi.fn(),
    mockedUpsertBadgeRuleApprovalPolicy: vi.fn(),
    mockedCreateBadgeRuleApproverGroup: vi.fn(),
    mockedAddBadgeRuleApproverGroupMember: vi.fn(),
    mockedListBadgeRuleApproverGroupsWithMembers: vi.fn(),
    mockedRemoveBadgeRuleApproverGroupMember: vi.fn(),
    mockedRemoveBadgeRuleApproverGroup: vi.fn(),
  };
});

export {
  mockedCreateLearnerRecordImportPreview,
  mockedDeleteDraftBadgeIssuanceRule,
  mockedEnqueueJobQueueMessageOnce,
  mockedFindActiveLearnerRecordImportPreview,
  mockedFindLearnerProfileById,
  mockedFindLearnerProfileByIdentity,
  mockedListLearnerProfilesForRecordLookup,
  mockedFindTenantAuthPolicy,
  mockedFindTenantLmsConnectionById,
  mockedGetTenantReportingComparisons,
  mockedGetTenantReportingEngagementCounts,
  mockedGetTenantReportingOverview,
  mockedGetTenantReportingTrends,
  mockedListAccessibleTenantContextsForUser,
  mockedListImportLearnerRecordBatchQueueMessages,
  mockedListLearnerRecordAssertionExports,
  mockedListLearnerRecordEntries,
  mockedListTenantAuthProviders,
  mockedListTenantBreakGlassAccounts,
  mockedListTenantLmsConnections,
  mockedListTenantMembers,
  mockedMarkLearnerRecordImportPreviewQueued,
  mockedResolveBetterAuthPrincipal,
  mockedResolveBetterAuthRequestedTenant,
  mockedDecideBadgeIssuanceRuleVersion,
  mockedReopenApprovedBadgeIssuanceRuleVersion,
  mockedWithdrawBadgeIssuanceRuleVersionSubmission,
  mockedRecertifyBadgeIssuanceRuleVersion,
  mockedFindBadgeIssuanceRuleBuilderDraft,
  mockedListBadgeIssuanceRuleBuilderDraftsForUser,
  mockedDeleteBadgeIssuanceRuleBuilderDraftById,
  mockedFindBadgeIssuanceRuleVersionById,
  mockedFindLtiResourceLinkPlacementForRule,
  mockedListActiveLtiLaunchSessionsForPlatform,
  mockedListBadgeIssuanceRuleVersionApprovalSteps,
  mockedListBadgeIssuanceRuleVersionApprovalEvents,
  mockedListPendingBadgeIssuanceRuleApprovalsForActor,
  mockedResolveBadgeRuleApprovalPolicy,
  mockedResolveTenantDefaultBadgeRuleApprovalPolicy,
  mockedCreateBadgeRuleApproverGroup,
  mockedAddBadgeRuleApproverGroupMember,
  mockedListBadgeRuleApproverGroupsWithMembers,
  mockedRemoveBadgeRuleApproverGroupMember,
  mockedRemoveBadgeRuleApproverGroup,
  mockedSubmitBadgeIssuanceRuleVersionForApproval,
  mockedUpsertBadgeRuleApprovalPolicy,
};

vi.mock("@credtrail/db", async () => {
  const actual = await vi.importActual<typeof import("@credtrail/db")>("@credtrail/db");

  return {
    ...actual,
    findLearnerProfileById: mockedFindLearnerProfileById,
    findLearnerProfileByIdentity: mockedFindLearnerProfileByIdentity,
    listLearnerProfilesForRecordLookup: mockedListLearnerProfilesForRecordLookup,
    createLearnerRecordImportPreview: mockedCreateLearnerRecordImportPreview,
    enqueueJobQueueMessageOnce: mockedEnqueueJobQueueMessageOnce,
    findActiveLearnerRecordImportPreview: mockedFindActiveLearnerRecordImportPreview,
    findTenantAuthPolicy: mockedFindTenantAuthPolicy,
    findTenantById: vi.fn(),
    findTenantMembership: vi.fn(),
    findUserById: vi.fn(),
    getTenantReportingEngagementCounts: mockedGetTenantReportingEngagementCounts,
    getTenantReportingOverview: mockedGetTenantReportingOverview,
    getTenantReportingTrends: mockedGetTenantReportingTrends,
    listImportLearnerRecordBatchQueueMessages: mockedListImportLearnerRecordBatchQueueMessages,
    listDelegatedIssuingAuthorityGrants: vi.fn(),
    listAccessibleTenantContextsForUser: mockedListAccessibleTenantContextsForUser,
    listLearnerRecordAssertionExports: mockedListLearnerRecordAssertionExports,
    listLearnerRecordEntries: mockedListLearnerRecordEntries,
    listBadgeIssuanceRules: vi.fn(),
    listBadgeIssuanceRuleVersions: vi.fn(),
    findBadgeIssuanceRuleVersionById: mockedFindBadgeIssuanceRuleVersionById,
    findBadgeIssuanceRuleBuilderDraftById: mockedFindBadgeIssuanceRuleBuilderDraft,
    findBadgeIssuanceRuleBuilderDraftForRule: mockedFindBadgeIssuanceRuleBuilderDraft,
    listBadgeIssuanceRuleBuilderDraftsForUser: mockedListBadgeIssuanceRuleBuilderDraftsForUser,
    deleteBadgeIssuanceRuleBuilderDraftById: mockedDeleteBadgeIssuanceRuleBuilderDraftById,
    findLtiResourceLinkPlacementForRule: mockedFindLtiResourceLinkPlacementForRule,
    listActiveLtiLaunchSessionsForPlatform: mockedListActiveLtiLaunchSessionsForPlatform,
    submitBadgeIssuanceRuleVersionForApproval: mockedSubmitBadgeIssuanceRuleVersionForApproval,
    resolveBadgeRuleApprovalPolicy: mockedResolveBadgeRuleApprovalPolicy,
    resolveTenantDefaultBadgeRuleApprovalPolicy: mockedResolveTenantDefaultBadgeRuleApprovalPolicy,
    upsertBadgeRuleApprovalPolicy: mockedUpsertBadgeRuleApprovalPolicy,
    createBadgeRuleApproverGroup: mockedCreateBadgeRuleApproverGroup,
    addBadgeRuleApproverGroupMember: mockedAddBadgeRuleApproverGroupMember,
    listBadgeRuleApproverGroupsWithMembers: mockedListBadgeRuleApproverGroupsWithMembers,
    removeBadgeRuleApproverGroupMember: mockedRemoveBadgeRuleApproverGroupMember,
    removeBadgeRuleApproverGroup: mockedRemoveBadgeRuleApproverGroup,
    listBadgeIssuanceRuleVersionApprovalSteps: mockedListBadgeIssuanceRuleVersionApprovalSteps,
    listBadgeIssuanceRuleVersionApprovalEvents: mockedListBadgeIssuanceRuleVersionApprovalEvents,
    listPendingBadgeIssuanceRuleApprovalsForActor:
      mockedListPendingBadgeIssuanceRuleApprovalsForActor,
    decideBadgeIssuanceRuleVersion: mockedDecideBadgeIssuanceRuleVersion,
    reopenApprovedBadgeIssuanceRuleVersion: mockedReopenApprovedBadgeIssuanceRuleVersion,
    withdrawBadgeIssuanceRuleVersionSubmission: mockedWithdrawBadgeIssuanceRuleVersionSubmission,
    recertifyBadgeIssuanceRuleVersion: mockedRecertifyBadgeIssuanceRuleVersion,
    listBadgeIssuanceRuleEvaluations: vi.fn().mockResolvedValue([]),
    listBadgeIssuanceRuleValueLists: vi.fn().mockResolvedValue([]),
    deleteDraftBadgeIssuanceRule: mockedDeleteDraftBadgeIssuanceRule,
    createBadgeIssuanceRuleValueList: vi.fn(),
    findBadgeIssuanceRuleEvaluationById: vi.fn(),
    resolveBadgeIssuanceRuleEvaluationReview: vi.fn(),
    findBadgeIssuanceRuleById: vi.fn().mockResolvedValue(null),
    listTenantReportingComparisons: mockedGetTenantReportingComparisons,
    listTenantBreakGlassAccounts: mockedListTenantBreakGlassAccounts,
    listTenantMembers: mockedListTenantMembers,
    listTenantMembershipOrgUnitScopes: vi.fn(),
    listTenantAuthProviders: mockedListTenantAuthProviders,
    findTenantLmsConnectionById: mockedFindTenantLmsConnectionById,
    listTenantLmsConnections: mockedListTenantLmsConnections,
    createDelegatedIssuingAuthorityGrant: vi.fn(),
    findDelegatedIssuingAuthorityGrantById: vi.fn(),
    revokeDelegatedIssuingAuthorityGrant: vi.fn(),
    upsertTenantMembershipOrgUnitScope: vi.fn(),
    removeTenantMembershipOrgUnitScope: vi.fn(),
    createAuditLog: vi.fn(),
    createBadgeTemplate: vi.fn(),
    createBadgeTemplateImageRevision: vi.fn(),
    findBadgeTemplateById: vi.fn(),
    findBadgeTemplateImageRevisionById: vi.fn(),
    setBadgeTemplateArchivedState: vi.fn(),
    updateBadgeTemplate: vi.fn(),
    listAuditLogs: vi.fn(),
    listBadgeTemplateImageRevisions: vi.fn(),
    listBadgeTemplateOwnershipEvents: vi.fn(),
    countBadgeTemplateImageRevisions: vi.fn(),
    listBadgeTemplateImageRevisionCountsByTenant: vi.fn(),
    listBadgeTemplates: vi.fn(),
    listTenantApiKeys: vi.fn(),
    listTenantAssertions: vi.fn(),
    findAssertionById: vi.fn(),
    findAssertionIssuanceProvenanceByAssertionId: vi.fn(),
    findAssertionReportingAttributionByAssertionId: vi.fn(),
    findBadgeIssuanceRuleEvaluationByAssertionId: vi.fn(),
    findTenantOrgUnitById: vi.fn(),
    findUsersByIds: vi.fn(),
    listAssertionLifecycleEvents: vi.fn(),
    listAuditLogsForAssertion: vi.fn(),
    recordAssertionLifecycleTransition: vi.fn(),
    resolveAssertionLifecycleState: vi.fn(),
    createTenantApiKey: vi.fn(),
    revokeTenantApiKey: vi.fn(),
    upsertTenantLmsConnection: vi.fn(),
    listTenantOrgUnits: vi.fn(),
    markLearnerRecordImportPreviewQueued: mockedMarkLearnerRecordImportPreviewQueued,
  };
});

vi.mock("@credtrail/db/postgres", () => {
  return {
    createPostgresDatabase: vi.fn(),
  };
});

vi.mock("../auth/better-auth-adapter", async () => {
  const actual = await vi.importActual<typeof import("../auth/better-auth-adapter")>(
    "../auth/better-auth-adapter",
  );

  return {
    ...actual,
    createBetterAuthProvider: vi.fn(() => ({
      requestMagicLink: vi.fn(),
      createMagicLinkSession: vi.fn(),
      createLtiSession: vi.fn(),
      resolveAuthenticatedPrincipal: mockedResolveBetterAuthPrincipal,
      resolveRequestedTenantContext: mockedResolveBetterAuthRequestedTenant,
      revokeCurrentSession: vi.fn(() => Promise.resolve()),
    })),
  };
});
